Iter9
kbannyi/shortener pull request #9
Opened 2024-07-29 20:37 UTC by kbannyi

2024-07-31 08:52 UTC, tmvrus requested changes
есть небольшие замечания

2024-07-31 08:52 UTC, tmvrus commented on cmd/shortener/main.go
> +		logger.Log.Error(err)
тут можно использовать Fatal будет ну одну строку короче

2024-07-31 08:52 UTC, tmvrus commented on cmd/shortener/main.go
> +	}
а как можно пользоваться логером если не получилось его инициализировать?

2024-07-31 08:52 UTC, tmvrus commented on internal/router/router.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
потерян return?

2024-07-31 08:52 UTC, tmvrus commented on internal/router/router.go
> +		http.Error(w, "url is required", http.StatusBadRequest)
потерян return?

2024-07-31 08:52 UTC, tmvrus commented on internal/router/router.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
и тут?

2024-08-01 07:24 UTC, kbannyi commented on cmd/shortener/main.go
> +	}
потерян return, поправил

2024-08-01 07:25 UTC, kbannyi commented on internal/router/router.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
поправил

2024-08-01 07:25 UTC, kbannyi commented on internal/router/router.go
> +		http.Error(w, "url is required", http.StatusBadRequest)
поправил

2024-08-01 07:25 UTC, kbannyi commented on internal/router/router.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
поправил

2024-08-01 07:33 UTC, kbannyi commented on cmd/shortener/main.go
> +		logger.Log.Error(err)
Я подумал и решил, что мне не очень нравится этот метод Fatal. Насколько я понял, он пропустит deferred функции, если таковые будут. Тут таких нет, но если добавлю, могу забыть проверить наличие Fatal-ов

// Остальные return-ы потерял, видимо, потому что там изначально были паники, которые я неосторожно заменил логами

2024-08-02 10:13 UTC, tmvrus approved these changes
зря используешься force-push, так вот привыкнешь а коллеги по команде не одобрят )

2024-08-11 08:30 UTC, merged